name: domain
description: "Core layer defining business logic, models and abstract repository interfaces."

publish_to: "none"

version: "1.0.0"

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ^3.29.0

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
